### ISSUE TITLE
Compilation error on Xcode 11.2

### ISSUE THREAD

**Issue by nex-derek** [Survicate/survicate-ios-sdk#11]
Here are the error and some additional information. Please let me know if any more information is needed, thanks!
Error: Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/derekcheung/nex/raptors-working/Pods/Survicate/Survicate.framework/Modules/Survicate.swiftmodule/arm64-apple-ios.swiftmodule

MacOS version: Mojave 10.14.6
Xcode version: 11.2 (11B52)
Cocoapods version: 1.8.3
Survicate version: 1.1.6

**Comment by rjstelling** [comment]
Survicate needs to set the **Build Libraries for Distribution** option to **Yes** in the framework's build settings, otherwise the swift compiler doesn't generate the necessary `.swiftinterface` files which are the key to future compilers being able to load your old library.

`BUILD_LIBRARY_FOR_DISTRIBUTION = YES;`

I'm hoping one of the developers can give an update on when we can expect an update. We've had to remove the framework in order to ship vital updates.

**Comment by j-brzozowski** [comment]
@nex-derek we just released 1.1.7 version.
@rjstelling option is now set to **Yes**, thanks for the advice.
